# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template actions.py.jinja --
from typing import TypeVar
import warnings

from . import types, errors, bases

if TYPE_CHECKING:
    from .client import Client
    from .bases import _PrismaModel


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class ItemsActions(Generic[_PrismaModelT]):
    __slots__ = (
        '_client',
        '_model',
    )

    def __init__(self, client: 'Client', model: Type[_PrismaModelT]) -> None:
        self._client = client
        self._model = model

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[_PrismaModelT]:
        """Execute a raw SQL query

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        List[prisma.models.Items]
            The records returned by the SQL query

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        users = await Items.prisma().query_raw(
            'SELECT * FROM Items WHERE id = $1',
            'bbadfchfja',
        )
        ```
        """
        return await self._client.query_raw(query, *args, model=self._model)

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> Optional[_PrismaModelT]:
        """Execute a raw SQL query, returning the first result

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        prisma.models.Items
            The first record returned by the SQL query
        None
            The raw SQL query did not return any records

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        user = await Items.prisma().query_first(
            'SELECT * FROM Items WHERE created_at = $1',
            datetime.datetime.utcnow(),
        )
        ```
        """
        return await self._client.query_first(query, *args, model=self._model)

    async def create(
        self,
        data: types.ItemsCreateInput,
        include: Optional[types.ItemsInclude] = None
    ) -> _PrismaModelT:
        """Create a new Items record.

        Parameters
        ----------
        data
            Items record data
        include
            Specifies which relations should be loaded on the returned Items model

        Returns
        -------
        prisma.models.Items
            The created Items record

        Raises
        ------
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # create a Items record from just the required fields
        items = await Items.prisma().create(
            data={
                # data to create a Items record
                'name': 'dhheabfhf',
                'price': 7953889008,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='create',
            model=self._model,
            arguments={
                'data': data,
                'include': include,
            },
        )
        return self._model.parse_obj(resp['data']['result'])

    async def create_many(
        self,
        data: List[types.ItemsCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> int:
        """Create multiple Items records at once.

        This function is *not* available when using SQLite.

        Parameters
        ----------
        data
            List of Items record data
        skip_duplicates
            Boolean flag for ignoring unique constraint errors

        Returns
        -------
        int
            The total number of records created

        Raises
        ------
        prisma.errors.UnsupportedDatabaseError
            Attempting to query when using SQLite
        prisma.errors.UniqueViolationError
            A unique constraint check has failed, these can be ignored with the `skip_duplicates` argument
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        total = await Items.prisma().create_many(
            data=[
                {
                    # data to create a Items record
                    'name': 'bbehjachib',
                    'price': 24420185688,
                },
                {
                    # data to create a Items record
                    'name': 'dgiiaaijj',
                    'price': 18096359424,
                },
            ],
            skip_duplicates=True,
        )
        ```
        """
        if self._client._active_provider == 'sqlite':
            raise errors.UnsupportedDatabaseError('sqlite', 'create_many()')

        resp = await self._client._execute(
            method='create_many',
            model=self._model,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    async def delete(
        self,
        where: types.ItemsWhereUniqueInput,
        include: Optional[types.ItemsInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Delete a single Items record.

        Parameters
        ----------
        where
            Items filter to select the record to be deleted, must be unique
        include
            Specifies which relations should be loaded on the returned Items model

        Returns
        -------
        prisma.models.Items
            The deleted Items record
        None
            Could not find a record to delete

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        items = await Items.prisma().delete(
            where={
                'id': 'eigcfgbif',
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='delete',
                model=self._model,
                arguments={
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return self._model.parse_obj(resp['data']['result'])

    async def find_unique(
        self,
        where: types.ItemsWhereUniqueInput,
        include: Optional[types.ItemsInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Find a unique Items record.

        Parameters
        ----------
        where
            Items filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned Items model

        Returns
        -------
        prisma.models.Items
            The found Items record
        None
            No record matching the given input could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        items = await Items.prisma().find_unique(
            where={
                'id': 'bagcfbhiig',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None
        return self._model.parse_obj(result)

    async def find_unique_or_raise(
        self,
        where: types.ItemsWhereUniqueInput,
        include: Optional[types.ItemsInclude] = None
    ) -> _PrismaModelT:
        """Find a unique Items record. Raises `RecordNotFoundError` if no record is found.

        Parameters
        ----------
        where
            Items filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned Items model

        Returns
        -------
        prisma.models.Items
            The found Items record

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        items = await Items.prisma().find_unique_or_raise(
            where={
                'id': 'cghideieh',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique_or_raise',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        return self._model.parse_obj(resp['data']['result'])

    async def find_many(
        self,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.ItemsWhereInput] = None,
        cursor: Optional[types.ItemsWhereUniqueInput] = None,
        include: Optional[types.ItemsInclude] = None,
        order: Optional[Union[types.ItemsOrderByInput, List[types.ItemsOrderByInput]]] = None,
        distinct: Optional[List[types.ItemsScalarFieldKeys]] = None,
    ) -> List[_PrismaModelT]:
        """Find multiple Items records.

        An empty list is returned if no records could be found.

        Parameters
        ----------
        take
            Limit the maximum number of Items records returned
        skip
            Ignore the first N results
        where
            Items filter to select records
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned Items model
        order
            Order the returned Items records by any field
        distinct
            Filter Items records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        List[prisma.models.Items]
            The list of all Items records that could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the first 10 Items records
        items = await Items.prisma().find_many(take=10)

        # find the first 5 Items records ordered by the name field
        items = await Items.prisma().find_many(
            take=5,
            order={
                'name': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_many',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return [self._model.parse_obj(r) for r in resp['data']['result']]

    async def find_first(
        self,
        skip: Optional[int] = None,
        where: Optional[types.ItemsWhereInput] = None,
        cursor: Optional[types.ItemsWhereUniqueInput] = None,
        include: Optional[types.ItemsInclude] = None,
        order: Optional[Union[types.ItemsOrderByInput, List[types.ItemsOrderByInput]]] = None,
        distinct: Optional[List[types.ItemsScalarFieldKeys]] = None,
    ) -> Optional[_PrismaModelT]:
        """Find a single Items record.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            Items filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned Items model
        order
            Order the returned Items records by any field
        distinct
            Filter Items records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.Items
            The first Items record found, matching the given arguments
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second Items record ordered by the price field
        items = await Items.prisma().find_first(
            skip=1,
            order={
                'price': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None
        return self._model.parse_obj(result)

    async def find_first_or_raise(
        self,
        skip: Optional[int] = None,
        where: Optional[types.ItemsWhereInput] = None,
        cursor: Optional[types.ItemsWhereUniqueInput] = None,
        include: Optional[types.ItemsInclude] = None,
        order: Optional[Union[types.ItemsOrderByInput, List[types.ItemsOrderByInput]]] = None,
        distinct: Optional[List[types.ItemsScalarFieldKeys]] = None,
    ) -> _PrismaModelT:
        """Find a single Items record. Raises `RecordNotFoundError` if no record was found.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            Items filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned Items model
        order
            Order the returned Items records by any field
        distinct
            Filter Items records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.Items
            The first Items record found, matching the given arguments

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second Items record ordered by the id field
        items = await Items.prisma().find_first_or_raise(
            skip=1,
            order={
                'id': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first_or_raise',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return self._model.parse_obj(resp['data']['result'])

    async def update(
        self,
        data: types.ItemsUpdateInput,
        where: types.ItemsWhereUniqueInput,
        include: Optional[types.ItemsInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Update a single Items record.

        Parameters
        ----------
        data
            Items record data specifying what to update
        where
            Items filter to select the unique record to create / update
        include
            Specifies which relations should be loaded on the returned Items model

        Returns
        -------
        prisma.models.Items
            The updated Items record
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        items = await Items.prisma().update(
            where={
                'id': 'biabhbdai',
            },
            data={
                # data to update the Items record to
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='update',
                model=self._model,
                arguments={
                    'data': data,
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return self._model.parse_obj(resp['data']['result'])

    async def upsert(
        self,
        where: types.ItemsWhereUniqueInput,
        data: types.ItemsUpsertInput,
        include: Optional[types.ItemsInclude] = None,
    ) -> _PrismaModelT:
        """Updates an existing record or create a new one

        Parameters
        ----------
        where
            Items filter to select the unique record to create / update
        data
            Data specifying what fields to set on create and update
        include
            Specifies which relations should be loaded on the returned Items model

        Returns
        -------
        prisma.models.Items
            The created or updated Items record

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        items = await Items.prisma().upsert(
            where={
                'id': 'idghgaicb',
            },
            data={
                'create': {
                    'id': 'idghgaicb',
                    'name': 'dgiiaaijj',
                    'price': 18096359424,
                },
                'update': {
                    'name': 'dgiiaaijj',
                    'price': 18096359424,
                },
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='upsert',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )
        return self._model.parse_obj(resp['data']['result'])

    async def update_many(
        self,
        data: types.ItemsUpdateManyMutationInput,
        where: types.ItemsWhereInput,
    ) -> int:
        """Update multiple Items records

        Parameters
        ----------
        data
            Items data to update the selected Items records to
        where
            Filter to select the Items records to update

        Returns
        -------
        int
            The total number of Items records that were updated

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # update all Items records
        total = await Items.prisma().update_many(
            data={
                'created_at': datetime.datetime.utcnow()
            },
            where={}
        )
        ```
        """
        resp = await self._client._execute(
            method='update_many',
            model=self._model,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    @overload
    async def count(
        self,
        select: None = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.ItemsWhereInput] = None,
        cursor: Optional[types.ItemsWhereUniqueInput] = None,
    ) -> int:
        """Count the number of Items records present in the database

        Parameters
        ----------
        select
            Select the Items fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            Items filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.ItemsCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await Items.prisma().count()

        # results: prisma.types.ItemsCountAggregateOutput
        results = await Items.prisma().count(
            select={
                '_all': True,
                'name': True,
            },
        )
        ```
        """


    @overload
    async def count(
        self,
        select: types.ItemsCountAggregateInput,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.ItemsWhereInput] = None,
        cursor: Optional[types.ItemsWhereUniqueInput] = None,
    ) -> types.ItemsCountAggregateOutput:
        ...

    async def count(
        self,
        select: Optional[types.ItemsCountAggregateInput] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.ItemsWhereInput] = None,
        cursor: Optional[types.ItemsWhereUniqueInput] = None,
    ) -> Union[int, types.ItemsCountAggregateOutput]:
        """Count the number of Items records present in the database

        Parameters
        ----------
        select
            Select the Items fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            Items filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.ItemsCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await Items.prisma().count()

        # results: prisma.types.ItemsCountAggregateOutput
        results = await Items.prisma().count(
            select={
                '_all': True,
                'price': True,
            },
        )
        ```
        """

        # TODO: this selection building should be moved to the QueryBuilder
        #
        # note the distinction between checking for `not select` here and `select is None`
        # later is to handle the case that the given select dictionary is empty, this
        # is a limitation of our types.
        if not select:
            root_selection = ['_count { _all }']
        else:

            root_selection = [
                '_count {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))
            ]

        resp = await self._client._execute(
            method='count',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'cursor': cursor,
            },
            root_selection=root_selection,
        )

        if select is None:
            return cast(int, resp['data']['result']['_count']['_all'])
        else:
            return cast(types.ItemsCountAggregateOutput, resp['data']['result']['_count'])

    async def delete_many(
        self,
        where: Optional[types.ItemsWhereInput] = None
    ) -> int:
        """Delete multiple Items records.

        Parameters
        ----------
        where
            Optional Items filter to find the records to be deleted

        Returns
        -------
        int
            The total number of Items records that were deleted

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # delete all Items records
        total = await Items.prisma().delete_many()
        ```
        """
        resp = await self._client._execute(
            method='delete_many',
            model=self._model,
            arguments={'where': where},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    # TODO: make this easier to work with safely, currently output fields are typed as
    #       not required, we should refactor the return type
    # TODO: consider returning a Dict where the keys are a Tuple of the `by` selection
    # TODO: statically type that the order argument is required when take or skip are present
    async def group_by(
        self,
        by: List['types.ItemsScalarFieldKeys'],
        *,
        where: Optional['types.ItemsWhereInput'] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        avg: Optional['types.ItemsAvgAggregateInput'] = None,
        sum: Optional['types.ItemsSumAggregateInput'] = None,
        min: Optional['types.ItemsMinAggregateInput'] = None,
        max: Optional['types.ItemsMaxAggregateInput'] = None,
        having: Optional['types.ItemsScalarWhereWithAggregatesInput'] = None,
        count: Optional[Union[bool, 'types.ItemsCountAggregateInput']] = None,
        order: Optional[Union[Mapping['types.ItemsScalarFieldKeys', 'types.SortOrder'], List[Mapping['types.ItemsScalarFieldKeys', 'types.SortOrder']]]] = None,
    ) -> List['types.ItemsGroupByOutput']:
        """Group Items records by one or more field values and perform aggregations
        each group such as finding the average.

        Parameters
        ----------
        by
            List of scalar Items fields to group records by
        where
            Items filter to select records
        take
            Limit the maximum number of Items records returned
        skip
            Ignore the first N records
        avg
            Adds the average of all values of the specified fields to the `_avg` field
            in the returned data.
        sum
            Adds the sum of all values of the specified fields to the `_sum` field
            in the returned data.
        min
            Adds the smallest available value for the specified fields to the `_min` field
            in the returned data.
        max
            Adds the largest available value for the specified fields to the `_max` field
            in the returned data.
        count
            Adds a count of non-fields to the `_count` field in the returned data.
        having
            Allows you to filter groups by an aggregate value - for example only return
            groups having an average age less than 50.
        order
            Lets you order the returned list by any property that is also present in `by`.
            Only **one** field is allowed at a time.

        Returns
        -------
        List[prisma.types.ItemsGroupByOutput]
            A list of dictionaries representing the Items record,
            this will also have additional fields present if aggregation arguments
            are used (see the above parameters)

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # group Items records by id values
        # and count how many records are in each group
        results = await Items.prisma().group_by(
            ['id'],
            count=True,
        )
        ```
        """
        if order is None:
            if take is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'take\' is present')

            if skip is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'skip\' is present')

        root_selection: List[str] = [*by]
        if avg is not None:
            root_selection.append(_select_fields('_avg', avg))

        if min is not None:
            root_selection.append(_select_fields('_min', min))

        if sum is not None:
            root_selection.append(_select_fields('_sum', sum))

        if max is not None:
            root_selection.append(_select_fields('_max', max))

        if count is not None:
            if count is True:
                root_selection.append('_count { _all }')
            elif isinstance(count, dict):
                root_selection.append(_select_fields('_count', count))

        resp = await self._client._execute(
            method='group_by',
            model=self._model,
            arguments={
                'by': by,
                'take': take,
                'skip': skip,
                'where': where,
                'having': having,
                'orderBy': order,
            },
            root_selection=root_selection,
        )
        return resp['data']['result']  # type: ignore[no-any-return]



def _select_fields(root: str, select: Mapping[str, Any]) -> str:
    """Helper to build a GraphQL selection string

    This is a work around until field selection is added to the query builder.
    """

    return root + ' {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))


from . import models